import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'PDF Toolkit',
      'dashboard': 'Dashboard',
      'tools': 'Tools',
      'saved_files': 'Saved Files',
      'settings': 'Settings',
      'total_created': 'Total Created',
      'total_merged': 'Total Merged',
      'total_compressed': 'Total Compressed',
      'storage_used': 'Storage Used',
      'recent_activity': 'Recent Activity',
      'quick_actions': 'Quick Actions',
      'image_to_pdf': 'Image to PDF',
      'merge_pdf': 'PDF Merger',
      'split_pdf': 'PDF Splitter',
      'compress_pdf': 'PDF Compressor',
      'rotate_pages': 'Page Rotation',
      'password_protect': 'Password Protect',
      'doc_scanner': 'Document Scanner',
      'no_recent_activity': 'No recent activity recorded.',
      'dark_mode': 'Dark Mode',
      'language': 'Language',
      'storage_location': 'Custom Storage Path',
      'backup_restore': 'Backup & Restore',
      'export_history': 'Export History',
      'export_history_success': 'Activity history exported successfully!',
      'backup_success': 'Backup created successfully!',
      'restore_success': 'Backup restored successfully!',
      'select_files': 'Select Files',
      'merge_files': 'Merge Files',
      'split_settings': 'Split Settings',
      'compress_level': 'Compression Level',
      'add_password': 'Add Password',
      'remove_password': 'Remove Password',
      'scan_doc': 'Scan Document',
      'search_files': 'Search files...',
      'favorites': 'Favorites',
      'empty_favorites': 'No favorite PDFs yet.',
      'empty_files': 'No generated PDFs found.',
      'sort_by': 'Sort By',
      'name': 'Name',
      'date': 'Date',
      'size': 'Size',
      'quality': 'Quality',
      'page_size': 'Page Size',
      'save': 'Save',
      'cancel': 'Cancel',
      'rename': 'Rename',
      'delete': 'Delete',
      'share': 'Share',
      'original': 'Original',
      'high': 'High',
      'medium': 'Medium',
      'low': 'Low',
      'rotate': 'Rotate',
      'selected': 'selected',
      'enter_password': 'Enter password...',
      'incorrect_password': 'Incorrect password. Try again.',
      'success': 'Success',
      'error': 'Error',
      'file_saved': 'File saved successfully to:',
    },
    'es': {
      'app_title': 'PDF Toolkit',
      'dashboard': 'Panel',
      'tools': 'Herramientas',
      'saved_files': 'Archivos',
      'settings': 'Ajustes',
      'total_created': 'Total Creado',
      'total_merged': 'Total Fusionado',
      'total_compressed': 'Total Comprimido',
      'storage_used': 'Almacenamiento',
      'recent_activity': 'Actividad Reciente',
      'quick_actions': 'Acciones Rápidas',
      'image_to_pdf': 'Imagen a PDF',
      'merge_pdf': 'Fusionar PDF',
      'split_pdf': 'Dividir PDF',
      'compress_pdf': 'Comprimir PDF',
      'rotate_pages': 'Rotar Páginas',
      'password_protect': 'Proteger Contraseña',
      'doc_scanner': 'Escáner de Docs',
      'no_recent_activity': 'No hay actividad reciente.',
      'dark_mode': 'Modo Oscuro',
      'language': 'Idioma',
      'storage_location': 'Ruta de Guardado',
      'backup_restore': 'Copia de Seguridad',
      'export_history': 'Exportar Historial',
      'export_history_success': '¡Historial de actividad exportado!',
      'backup_success': '¡Copia creada con éxito!',
      'restore_success': '¡Copia restaurada con éxito!',
      'select_files': 'Seleccionar',
      'merge_files': 'Fusionar',
      'split_settings': 'Ajustes de División',
      'compress_level': 'Nivel de Compresión',
      'add_password': 'Añadir Contraseña',
      'remove_password': 'Quitar Contraseña',
      'scan_doc': 'Escanear',
      'search_files': 'Buscar...',
      'favorites': 'Favoritos',
      'empty_favorites': 'No hay favoritos.',
      'empty_files': 'No hay archivos generados.',
      'sort_by': 'Ordenar Por',
      'name': 'Nombre',
      'date': 'Fecha',
      'size': 'Tamaño',
      'quality': 'Calidad',
      'page_size': 'Tamaño de Página',
      'save': 'Guardar',
      'cancel': 'Cancelar',
      'rename': 'Renombrar',
      'delete': 'Eliminar',
      'share': 'Compartir',
      'original': 'Original',
      'high': 'Alto',
      'medium': 'Medio',
      'low': 'Bajo',
      'rotate': 'Rotar',
      'selected': 'seleccionado',
      'enter_password': 'Contraseña...',
      'incorrect_password': 'Contraseña incorrecta.',
      'success': 'Éxito',
      'error': 'Error',
      'file_saved': 'Archivo guardado con éxito en:',
    },
    'fr': {
      'app_title': 'PDF Toolkit',
      'dashboard': 'Tableau de bord',
      'tools': 'Outils',
      'saved_files': 'Fichiers',
      'settings': 'Paramètres',
      'total_created': 'Total Créé',
      'total_merged': 'Total Fusionné',
      'total_compressed': 'Total Compressé',
      'storage_used': 'Stockage Utilisé',
      'recent_activity': 'Activité Récente',
      'quick_actions': 'Actions Rapides',
      'image_to_pdf': 'Image en PDF',
      'merge_pdf': 'Fusionner PDF',
      'split_pdf': 'Diviser PDF',
      'compress_pdf': 'Compresser PDF',
      'rotate_pages': 'Rotation de Pages',
      'password_protect': 'Mot de Passe',
      'doc_scanner': 'Scanner de Doc',
      'no_recent_activity': 'Aucune activité récente.',
      'dark_mode': 'Mode Sombre',
      'language': 'Langue',
      'storage_location': 'Chemin de Stockage',
      'backup_restore': 'Sauvegarde & Restauration',
      'export_history': 'Exporter l\'Historique',
      'export_history_success': 'Historique exporté avec succès!',
      'backup_success': 'Sauvegarde créée avec succès!',
      'restore_success': 'Sauvegarde restaurée avec succès!',
      'select_files': 'Sélectionner',
      'merge_files': 'Fusionner',
      'split_settings': 'Paramètres de Division',
      'compress_level': 'Niveau de Compression',
      'add_password': 'Ajouter Mot de Passe',
      'remove_password': 'Retirer Mot de Passe',
      'scan_doc': 'Scanner le Document',
      'search_files': 'Rechercher...',
      'favorites': 'Favoris',
      'empty_favorites': 'Aucun favori pour le moment.',
      'empty_files': 'Aucun PDF trouvé.',
      'sort_by': 'Trier Par',
      'name': 'Nom',
      'date': 'Date',
      'size': 'Taille',
      'quality': 'Qualité',
      'page_size': 'Taille de Page',
      'save': 'Enregistrer',
      'cancel': 'Annuler',
      'rename': 'Renommer',
      'delete': 'Supprimer',
      'share': 'Partager',
      'original': 'Original',
      'high': 'Élevé',
      'medium': 'Moyen',
      'low': 'Faible',
      'rotate': 'Faire pivoter',
      'selected': 'sélectionné',
      'enter_password': 'Mot de passe...',
      'incorrect_password': 'Mot de passe incorrect.',
      'success': 'Succès',
      'error': 'Erreur',
      'file_saved': 'Fichier enregistré avec succès sous:',
    },
    'de': {
      'app_title': 'PDF Toolkit',
      'dashboard': 'Dashboard',
      'tools': 'Werkzeuge',
      'saved_files': 'Dateien',
      'settings': 'Einstellungen',
      'total_created': 'Gesamt Erstellt',
      'total_merged': 'Gesamt Zusammengeführt',
      'total_compressed': 'Gesamt Komprimiert',
      'storage_used': 'Speicherplatz',
      'recent_activity': 'Letzte Aktivität',
      'quick_actions': 'Schnellzugriff',
      'image_to_pdf': 'Bild zu PDF',
      'merge_pdf': 'PDF Zusammenführen',
      'split_pdf': 'PDF Aufteilen',
      'compress_pdf': 'PDF Komprimieren',
      'rotate_pages': 'Seiten Rotieren',
      'password_protect': 'Passwortschutz',
      'doc_scanner': 'Dokumentenscanner',
      'no_recent_activity': 'Keine letzten Aktivitäten.',
      'dark_mode': 'Dunkelmodus',
      'language': 'Sprache',
      'storage_location': 'Speicherort',
      'backup_restore': 'Sicherung & Wiederherstellung',
      'export_history': 'Verlauf Exportieren',
      'export_history_success': 'Aktivitätsverlauf erfolgreich exportiert!',
      'backup_success': 'Sicherung erfolgreich erstellt!',
      'restore_success': 'Sicherung erfolgreich wiederhergestellt!',
      'select_files': 'Dateien Wählen',
      'merge_files': 'Zusammenführen',
      'split_settings': 'Aufteilungs-Optionen',
      'compress_level': 'Komprimierungsstufe',
      'add_password': 'Passwort Hinzufügen',
      'remove_password': 'Passwort Entfernen',
      'scan_doc': 'Scannen',
      'search_files': 'Suchen...',
      'favorites': 'Favoriten',
      'empty_favorites': 'Keine Favoriten.',
      'empty_files': 'Keine PDFs gefunden.',
      'sort_by': 'Sortieren Nach',
      'name': 'Name',
      'date': 'Datum',
      'size': 'Größe',
      'quality': 'Qualität',
      'page_size': 'Seitengröße',
      'save': 'Speichern',
      'cancel': 'Abbrechen',
      'rename': 'Umbenennen',
      'delete': 'Löschen',
      'share': 'Teilen',
      'original': 'Original',
      'high': 'Hoch',
      'medium': 'Mittel',
      'low': 'Niedrig',
      'rotate': 'Drehen',
      'selected': 'ausgewählt',
      'enter_password': 'Passwort eingeben...',
      'incorrect_password': 'Falsches Passwort.',
      'success': 'Erfolg',
      'error': 'Fehler',
      'file_saved': 'Datei erfolgreich gespeichert unter:',
    },
    'hi': {
      'app_title': 'PDF Toolkit',
      'dashboard': 'डैशबोर्ड',
      'tools': 'टूल्स',
      'saved_files': 'फाइलें',
      'settings': 'सेटिंग्स',
      'total_created': 'कुल निर्मित',
      'total_merged': 'कुल मर्ज किया गया',
      'total_compressed': 'कुल संपीड़ित',
      'storage_used': 'संग्रहण उपयोग',
      'recent_activity': 'हाल की गतिविधि',
      'quick_actions': 'त्वरित कार्रवाई',
      'image_to_pdf': 'छवि से PDF',
      'merge_pdf': 'PDF विलय (मर्ज)',
      'split_pdf': 'PDF विभाजन (स्प्लिट)',
      'compress_pdf': 'PDF संपीड़न',
      'rotate_pages': 'पेज घूर्णन',
      'password_protect': 'पासवर्ड सुरक्षा',
      'doc_scanner': 'दस्तावेज़ स्कैनर',
      'no_recent_activity': 'कोई हाल की गतिविधि दर्ज नहीं है।',
      'dark_mode': 'डार्क मोड',
      'language': 'भाषा',
      'storage_location': 'पसंदीदा संग्रहण स्थान',
      'backup_restore': 'बैकअप और पुनर्प्राप्ति',
      'export_history': 'इतिहास निर्यात करें',
      'export_history_success': 'गतिविधि इतिहास सफलतापूर्वक निर्यात किया गया!',
      'backup_success': 'बैकअप सफलतापूर्वक बनाया गया!',
      'restore_success': 'बैकअप सफलतापूर्वक पुनर्स्थापित हुआ!',
      'select_files': 'फाइलें चुनें',
      'merge_files': 'मर्ज करें',
      'split_settings': 'विभाजन सेटिंग्स',
      'compress_level': 'संपीड़न स्तर',
      'add_password': 'पासवर्ड जोड़ें',
      'remove_password': 'पासवर्ड हटाएं',
      'scan_doc': 'दस्तावेज़ स्कैन',
      'search_files': 'खोजें...',
      'favorites': 'पसंदीदा',
      'empty_favorites': 'कोई पसंदीदा PDF नहीं है।',
      'empty_files': 'कोई निर्मित PDF नहीं मिली।',
      'sort_by': 'क्रमबद्ध करें',
      'name': 'नाम',
      'date': 'दिनांक',
      'size': 'आकार',
      'quality': 'गुणवत्ता',
      'page_size': 'पेज का आकार',
      'save': 'सहेजें',
      'cancel': 'रद्द करें',
      'rename': 'नाम बदलें',
      'delete': 'हटाएं',
      'share': 'साझा करें',
      'original': 'मूल',
      'high': 'उच्च',
      'medium': 'मध्यम',
      'low': 'निम्न',
      'rotate': 'घुमाएं',
      'selected': 'चयनित',
      'enter_password': 'पासवर्ड डालें...',
      'incorrect_password': 'गलत पासवर्ड। पुनः प्रयास करें।',
      'success': 'सफलता',
      'error': 'त्रुटि',
      'file_saved': 'फ़ाइल यहाँ सफलतापूर्वक सहेजी गई:',
    }
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? _localizedValues['en']?[key] ?? key;
  }

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ?? AppLocalizations(const Locale('en'));
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'es', 'fr', 'de', 'hi'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) => Future.value(AppLocalizations(locale));

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}

// Riverpod locale provider
final localeProvider = StateNotifierProvider<LocaleNotifier, Locale>((ref) {
  return LocaleNotifier();
});

class LocaleNotifier extends StateNotifier<Locale> {
  LocaleNotifier() : super(const Locale('en'));

  void setLocale(Locale newLocale) {
    if (['en', 'es', 'fr', 'de', 'hi'].contains(newLocale.languageCode)) {
      state = newLocale;
    }
  }
}
